name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.14.4 <3.0.0"
dependencies:
  google_fonts: ^2.2.0
  get: ^4.3.8
  shared_preferences: ^2.0.8
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  flutter_staggered_grid_view: ^0.6.1

  rating_dialog: ^2.0.3
  flutter_svg: ^1.0.1
  share: ^2.0.4
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^3.5.3
  http: ^0.13.4
  image_picker: ^0.8.4+3
  cloud_firestore: ^3.1.17
  font_awesome_flutter: ^9.2.0
  firebase_storage: ^10.0.6
  url_launcher: ^6.1.4
  cached_network_image:
    git:
      url: https://github.com/lucasrueda/flutter_cached_network_image.git
      path: cached_network_image
      ref: develop
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^7.2.1
  badges: ^2.0.1
  flutter_bloc: ^7.3.1
  carousel_slider: ^4.0.0
  flutter_typeahead: 3.2.1
  folding_cell: "^1.0.2"
  flutter_holo_date_picker: ^1.0.3
  expansion_tile_card: ^1.1.0
  percent_indicator: ^2.1.3
  card_settings: ^3.0.0
  flutter_swiper: ^1.1.6
  webview_flutter: ^0.3.19+6
  screenshot: ^1.2.3
  carousel_pro: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/welcom.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icons/
    - assets/images/
    - assets/images/banners/
